/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.research.asynchronousratchetingtree.art.message.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-01-05")
public class CiphertextMessageStruct implements org.apache.thrift.TBase<CiphertextMessageStruct, CiphertextMessageStruct._Fields>, java.io.Serializable, Cloneable, Comparable<CiphertextMessageStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CiphertextMessageStruct");

  private static final org.apache.thrift.protocol.TField AUTHENTICATED_MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("authenticatedMessage", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField CIPHERTEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("ciphertext", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CiphertextMessageStructStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CiphertextMessageStructTupleSchemeFactory();

  public AuthenticatedMessageStruct authenticatedMessage; // required
  public java.nio.ByteBuffer ciphertext; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    AUTHENTICATED_MESSAGE((short)1, "authenticatedMessage"),
    CIPHERTEXT((short)2, "ciphertext");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // AUTHENTICATED_MESSAGE
          return AUTHENTICATED_MESSAGE;
        case 2: // CIPHERTEXT
          return CIPHERTEXT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.AUTHENTICATED_MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("authenticatedMessage", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "AuthenticatedMessageStruct")));
    tmpMap.put(_Fields.CIPHERTEXT, new org.apache.thrift.meta_data.FieldMetaData("ciphertext", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CiphertextMessageStruct.class, metaDataMap);
  }

  public CiphertextMessageStruct() {
  }

  public CiphertextMessageStruct(
    AuthenticatedMessageStruct authenticatedMessage,
    java.nio.ByteBuffer ciphertext)
  {
    this();
    this.authenticatedMessage = authenticatedMessage;
    this.ciphertext = org.apache.thrift.TBaseHelper.copyBinary(ciphertext);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CiphertextMessageStruct(CiphertextMessageStruct other) {
    if (other.isSetAuthenticatedMessage()) {
      this.authenticatedMessage = new AuthenticatedMessageStruct(other.authenticatedMessage);
    }
    if (other.isSetCiphertext()) {
      this.ciphertext = org.apache.thrift.TBaseHelper.copyBinary(other.ciphertext);
    }
  }

  public CiphertextMessageStruct deepCopy() {
    return new CiphertextMessageStruct(this);
  }

  @Override
  public void clear() {
    this.authenticatedMessage = null;
    this.ciphertext = null;
  }

  public AuthenticatedMessageStruct getAuthenticatedMessage() {
    return this.authenticatedMessage;
  }

  public CiphertextMessageStruct setAuthenticatedMessage(AuthenticatedMessageStruct authenticatedMessage) {
    this.authenticatedMessage = authenticatedMessage;
    return this;
  }

  public void unsetAuthenticatedMessage() {
    this.authenticatedMessage = null;
  }

  /** Returns true if field authenticatedMessage is set (has been assigned a value) and false otherwise */
  public boolean isSetAuthenticatedMessage() {
    return this.authenticatedMessage != null;
  }

  public void setAuthenticatedMessageIsSet(boolean value) {
    if (!value) {
      this.authenticatedMessage = null;
    }
  }

  public byte[] getCiphertext() {
    setCiphertext(org.apache.thrift.TBaseHelper.rightSize(ciphertext));
    return ciphertext == null ? null : ciphertext.array();
  }

  public java.nio.ByteBuffer bufferForCiphertext() {
    return org.apache.thrift.TBaseHelper.copyBinary(ciphertext);
  }

  public CiphertextMessageStruct setCiphertext(byte[] ciphertext) {
    this.ciphertext = ciphertext == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(ciphertext.clone());
    return this;
  }

  public CiphertextMessageStruct setCiphertext(java.nio.ByteBuffer ciphertext) {
    this.ciphertext = org.apache.thrift.TBaseHelper.copyBinary(ciphertext);
    return this;
  }

  public void unsetCiphertext() {
    this.ciphertext = null;
  }

  /** Returns true if field ciphertext is set (has been assigned a value) and false otherwise */
  public boolean isSetCiphertext() {
    return this.ciphertext != null;
  }

  public void setCiphertextIsSet(boolean value) {
    if (!value) {
      this.ciphertext = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case AUTHENTICATED_MESSAGE:
      if (value == null) {
        unsetAuthenticatedMessage();
      } else {
        setAuthenticatedMessage((AuthenticatedMessageStruct)value);
      }
      break;

    case CIPHERTEXT:
      if (value == null) {
        unsetCiphertext();
      } else {
        if (value instanceof byte[]) {
          setCiphertext((byte[])value);
        } else {
          setCiphertext((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case AUTHENTICATED_MESSAGE:
      return getAuthenticatedMessage();

    case CIPHERTEXT:
      return getCiphertext();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case AUTHENTICATED_MESSAGE:
      return isSetAuthenticatedMessage();
    case CIPHERTEXT:
      return isSetCiphertext();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CiphertextMessageStruct)
      return this.equals((CiphertextMessageStruct)that);
    return false;
  }

  public boolean equals(CiphertextMessageStruct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_authenticatedMessage = true && this.isSetAuthenticatedMessage();
    boolean that_present_authenticatedMessage = true && that.isSetAuthenticatedMessage();
    if (this_present_authenticatedMessage || that_present_authenticatedMessage) {
      if (!(this_present_authenticatedMessage && that_present_authenticatedMessage))
        return false;
      if (!this.authenticatedMessage.equals(that.authenticatedMessage))
        return false;
    }

    boolean this_present_ciphertext = true && this.isSetCiphertext();
    boolean that_present_ciphertext = true && that.isSetCiphertext();
    if (this_present_ciphertext || that_present_ciphertext) {
      if (!(this_present_ciphertext && that_present_ciphertext))
        return false;
      if (!this.ciphertext.equals(that.ciphertext))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetAuthenticatedMessage()) ? 131071 : 524287);
    if (isSetAuthenticatedMessage())
      hashCode = hashCode * 8191 + authenticatedMessage.hashCode();

    hashCode = hashCode * 8191 + ((isSetCiphertext()) ? 131071 : 524287);
    if (isSetCiphertext())
      hashCode = hashCode * 8191 + ciphertext.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(CiphertextMessageStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetAuthenticatedMessage()).compareTo(other.isSetAuthenticatedMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAuthenticatedMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.authenticatedMessage, other.authenticatedMessage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCiphertext()).compareTo(other.isSetCiphertext());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCiphertext()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ciphertext, other.ciphertext);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CiphertextMessageStruct(");
    boolean first = true;

    sb.append("authenticatedMessage:");
    if (this.authenticatedMessage == null) {
      sb.append("null");
    } else {
      sb.append(this.authenticatedMessage);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ciphertext:");
    if (this.ciphertext == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.ciphertext, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CiphertextMessageStructStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CiphertextMessageStructStandardScheme getScheme() {
      return new CiphertextMessageStructStandardScheme();
    }
  }

  private static class CiphertextMessageStructStandardScheme extends org.apache.thrift.scheme.StandardScheme<CiphertextMessageStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CiphertextMessageStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // AUTHENTICATED_MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.authenticatedMessage = new AuthenticatedMessageStruct();
              struct.authenticatedMessage.read(iprot);
              struct.setAuthenticatedMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CIPHERTEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ciphertext = iprot.readBinary();
              struct.setCiphertextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CiphertextMessageStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.authenticatedMessage != null) {
        oprot.writeFieldBegin(AUTHENTICATED_MESSAGE_FIELD_DESC);
        struct.authenticatedMessage.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.ciphertext != null) {
        oprot.writeFieldBegin(CIPHERTEXT_FIELD_DESC);
        oprot.writeBinary(struct.ciphertext);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CiphertextMessageStructTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CiphertextMessageStructTupleScheme getScheme() {
      return new CiphertextMessageStructTupleScheme();
    }
  }

  private static class CiphertextMessageStructTupleScheme extends org.apache.thrift.scheme.TupleScheme<CiphertextMessageStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CiphertextMessageStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetAuthenticatedMessage()) {
        optionals.set(0);
      }
      if (struct.isSetCiphertext()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetAuthenticatedMessage()) {
        struct.authenticatedMessage.write(oprot);
      }
      if (struct.isSetCiphertext()) {
        oprot.writeBinary(struct.ciphertext);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CiphertextMessageStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.authenticatedMessage = new AuthenticatedMessageStruct();
        struct.authenticatedMessage.read(iprot);
        struct.setAuthenticatedMessageIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ciphertext = iprot.readBinary();
        struct.setCiphertextIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

