/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.research.asynchronousratchetingtree.dhratchet.message.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-01-05")
public class DHRatchetMessageStruct implements org.apache.thrift.TBase<DHRatchetMessageStruct, DHRatchetMessageStruct._Fields>, java.io.Serializable, Cloneable, Comparable<DHRatchetMessageStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DHRatchetMessageStruct");

  private static final org.apache.thrift.protocol.TField PEER_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("peerNum", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField RATCHET_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("ratchetKey", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CIPHERTEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("ciphertext", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DHRatchetMessageStructStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DHRatchetMessageStructTupleSchemeFactory();

  public int peerNum; // required
  public java.nio.ByteBuffer ratchetKey; // required
  public java.nio.ByteBuffer ciphertext; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PEER_NUM((short)1, "peerNum"),
    RATCHET_KEY((short)2, "ratchetKey"),
    CIPHERTEXT((short)3, "ciphertext");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PEER_NUM
          return PEER_NUM;
        case 2: // RATCHET_KEY
          return RATCHET_KEY;
        case 3: // CIPHERTEXT
          return CIPHERTEXT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PEERNUM_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PEER_NUM, new org.apache.thrift.meta_data.FieldMetaData("peerNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.RATCHET_KEY, new org.apache.thrift.meta_data.FieldMetaData("ratchetKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.CIPHERTEXT, new org.apache.thrift.meta_data.FieldMetaData("ciphertext", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DHRatchetMessageStruct.class, metaDataMap);
  }

  public DHRatchetMessageStruct() {
  }

  public DHRatchetMessageStruct(
    int peerNum,
    java.nio.ByteBuffer ratchetKey,
    java.nio.ByteBuffer ciphertext)
  {
    this();
    this.peerNum = peerNum;
    setPeerNumIsSet(true);
    this.ratchetKey = org.apache.thrift.TBaseHelper.copyBinary(ratchetKey);
    this.ciphertext = org.apache.thrift.TBaseHelper.copyBinary(ciphertext);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DHRatchetMessageStruct(DHRatchetMessageStruct other) {
    __isset_bitfield = other.__isset_bitfield;
    this.peerNum = other.peerNum;
    if (other.isSetRatchetKey()) {
      this.ratchetKey = org.apache.thrift.TBaseHelper.copyBinary(other.ratchetKey);
    }
    if (other.isSetCiphertext()) {
      this.ciphertext = org.apache.thrift.TBaseHelper.copyBinary(other.ciphertext);
    }
  }

  public DHRatchetMessageStruct deepCopy() {
    return new DHRatchetMessageStruct(this);
  }

  @Override
  public void clear() {
    setPeerNumIsSet(false);
    this.peerNum = 0;
    this.ratchetKey = null;
    this.ciphertext = null;
  }

  public int getPeerNum() {
    return this.peerNum;
  }

  public DHRatchetMessageStruct setPeerNum(int peerNum) {
    this.peerNum = peerNum;
    setPeerNumIsSet(true);
    return this;
  }

  public void unsetPeerNum() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PEERNUM_ISSET_ID);
  }

  /** Returns true if field peerNum is set (has been assigned a value) and false otherwise */
  public boolean isSetPeerNum() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PEERNUM_ISSET_ID);
  }

  public void setPeerNumIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PEERNUM_ISSET_ID, value);
  }

  public byte[] getRatchetKey() {
    setRatchetKey(org.apache.thrift.TBaseHelper.rightSize(ratchetKey));
    return ratchetKey == null ? null : ratchetKey.array();
  }

  public java.nio.ByteBuffer bufferForRatchetKey() {
    return org.apache.thrift.TBaseHelper.copyBinary(ratchetKey);
  }

  public DHRatchetMessageStruct setRatchetKey(byte[] ratchetKey) {
    this.ratchetKey = ratchetKey == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(ratchetKey.clone());
    return this;
  }

  public DHRatchetMessageStruct setRatchetKey(java.nio.ByteBuffer ratchetKey) {
    this.ratchetKey = org.apache.thrift.TBaseHelper.copyBinary(ratchetKey);
    return this;
  }

  public void unsetRatchetKey() {
    this.ratchetKey = null;
  }

  /** Returns true if field ratchetKey is set (has been assigned a value) and false otherwise */
  public boolean isSetRatchetKey() {
    return this.ratchetKey != null;
  }

  public void setRatchetKeyIsSet(boolean value) {
    if (!value) {
      this.ratchetKey = null;
    }
  }

  public byte[] getCiphertext() {
    setCiphertext(org.apache.thrift.TBaseHelper.rightSize(ciphertext));
    return ciphertext == null ? null : ciphertext.array();
  }

  public java.nio.ByteBuffer bufferForCiphertext() {
    return org.apache.thrift.TBaseHelper.copyBinary(ciphertext);
  }

  public DHRatchetMessageStruct setCiphertext(byte[] ciphertext) {
    this.ciphertext = ciphertext == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(ciphertext.clone());
    return this;
  }

  public DHRatchetMessageStruct setCiphertext(java.nio.ByteBuffer ciphertext) {
    this.ciphertext = org.apache.thrift.TBaseHelper.copyBinary(ciphertext);
    return this;
  }

  public void unsetCiphertext() {
    this.ciphertext = null;
  }

  /** Returns true if field ciphertext is set (has been assigned a value) and false otherwise */
  public boolean isSetCiphertext() {
    return this.ciphertext != null;
  }

  public void setCiphertextIsSet(boolean value) {
    if (!value) {
      this.ciphertext = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PEER_NUM:
      if (value == null) {
        unsetPeerNum();
      } else {
        setPeerNum((java.lang.Integer)value);
      }
      break;

    case RATCHET_KEY:
      if (value == null) {
        unsetRatchetKey();
      } else {
        if (value instanceof byte[]) {
          setRatchetKey((byte[])value);
        } else {
          setRatchetKey((java.nio.ByteBuffer)value);
        }
      }
      break;

    case CIPHERTEXT:
      if (value == null) {
        unsetCiphertext();
      } else {
        if (value instanceof byte[]) {
          setCiphertext((byte[])value);
        } else {
          setCiphertext((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PEER_NUM:
      return getPeerNum();

    case RATCHET_KEY:
      return getRatchetKey();

    case CIPHERTEXT:
      return getCiphertext();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PEER_NUM:
      return isSetPeerNum();
    case RATCHET_KEY:
      return isSetRatchetKey();
    case CIPHERTEXT:
      return isSetCiphertext();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof DHRatchetMessageStruct)
      return this.equals((DHRatchetMessageStruct)that);
    return false;
  }

  public boolean equals(DHRatchetMessageStruct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_peerNum = true;
    boolean that_present_peerNum = true;
    if (this_present_peerNum || that_present_peerNum) {
      if (!(this_present_peerNum && that_present_peerNum))
        return false;
      if (this.peerNum != that.peerNum)
        return false;
    }

    boolean this_present_ratchetKey = true && this.isSetRatchetKey();
    boolean that_present_ratchetKey = true && that.isSetRatchetKey();
    if (this_present_ratchetKey || that_present_ratchetKey) {
      if (!(this_present_ratchetKey && that_present_ratchetKey))
        return false;
      if (!this.ratchetKey.equals(that.ratchetKey))
        return false;
    }

    boolean this_present_ciphertext = true && this.isSetCiphertext();
    boolean that_present_ciphertext = true && that.isSetCiphertext();
    if (this_present_ciphertext || that_present_ciphertext) {
      if (!(this_present_ciphertext && that_present_ciphertext))
        return false;
      if (!this.ciphertext.equals(that.ciphertext))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + peerNum;

    hashCode = hashCode * 8191 + ((isSetRatchetKey()) ? 131071 : 524287);
    if (isSetRatchetKey())
      hashCode = hashCode * 8191 + ratchetKey.hashCode();

    hashCode = hashCode * 8191 + ((isSetCiphertext()) ? 131071 : 524287);
    if (isSetCiphertext())
      hashCode = hashCode * 8191 + ciphertext.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(DHRatchetMessageStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPeerNum()).compareTo(other.isSetPeerNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPeerNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.peerNum, other.peerNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRatchetKey()).compareTo(other.isSetRatchetKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRatchetKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ratchetKey, other.ratchetKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCiphertext()).compareTo(other.isSetCiphertext());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCiphertext()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ciphertext, other.ciphertext);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DHRatchetMessageStruct(");
    boolean first = true;

    sb.append("peerNum:");
    sb.append(this.peerNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ratchetKey:");
    if (this.ratchetKey == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.ratchetKey, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ciphertext:");
    if (this.ciphertext == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.ciphertext, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DHRatchetMessageStructStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DHRatchetMessageStructStandardScheme getScheme() {
      return new DHRatchetMessageStructStandardScheme();
    }
  }

  private static class DHRatchetMessageStructStandardScheme extends org.apache.thrift.scheme.StandardScheme<DHRatchetMessageStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DHRatchetMessageStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PEER_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.peerNum = iprot.readI32();
              struct.setPeerNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RATCHET_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ratchetKey = iprot.readBinary();
              struct.setRatchetKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CIPHERTEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ciphertext = iprot.readBinary();
              struct.setCiphertextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DHRatchetMessageStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PEER_NUM_FIELD_DESC);
      oprot.writeI32(struct.peerNum);
      oprot.writeFieldEnd();
      if (struct.ratchetKey != null) {
        oprot.writeFieldBegin(RATCHET_KEY_FIELD_DESC);
        oprot.writeBinary(struct.ratchetKey);
        oprot.writeFieldEnd();
      }
      if (struct.ciphertext != null) {
        oprot.writeFieldBegin(CIPHERTEXT_FIELD_DESC);
        oprot.writeBinary(struct.ciphertext);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DHRatchetMessageStructTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DHRatchetMessageStructTupleScheme getScheme() {
      return new DHRatchetMessageStructTupleScheme();
    }
  }

  private static class DHRatchetMessageStructTupleScheme extends org.apache.thrift.scheme.TupleScheme<DHRatchetMessageStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DHRatchetMessageStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPeerNum()) {
        optionals.set(0);
      }
      if (struct.isSetRatchetKey()) {
        optionals.set(1);
      }
      if (struct.isSetCiphertext()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetPeerNum()) {
        oprot.writeI32(struct.peerNum);
      }
      if (struct.isSetRatchetKey()) {
        oprot.writeBinary(struct.ratchetKey);
      }
      if (struct.isSetCiphertext()) {
        oprot.writeBinary(struct.ciphertext);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DHRatchetMessageStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.peerNum = iprot.readI32();
        struct.setPeerNumIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ratchetKey = iprot.readBinary();
        struct.setRatchetKeyIsSet(true);
      }
      if (incoming.get(2)) {
        struct.ciphertext = iprot.readBinary();
        struct.setCiphertextIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

